name: Build and push image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/room-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Clean up
        if: always()
        run: |
          rm -f .env

